AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'forbidium.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
