AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'forbidium.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Metrics/LineLength:
  Max: 85
  Exclude:
    - 'spec/dummy/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
